package com.example.studygroup

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.foundation.layout.Box
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.test.ext.junit.runners.AndroidJUnit4
import components.AppButton
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith


/**
 * Instrumented tests for AppButton
 *
 * These are generated by ChatGPT
 */
@RunWith(AndroidJUnit4::class)
class AppButtonTest {

    @get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun `button has its text displayed`() {
        val buttonText = "Click Me"
        composeTestRule.setContent {
            AppButton(
                text = buttonText
            )
        }

        composeTestRule.onNodeWithText(buttonText).assertIsDisplayed()
    }

    @Test
    fun `callback is called when button is pressed`() {
        var clicked = false

        composeTestRule.setContent {
            AppButton(
                text = "Press",
                onClick = { clicked = true }
            )
        }

        composeTestRule.onNodeWithText("Press")
            .performClick()

        assert(clicked) { "Button onClick should have been called" }
    }

    @Test
    fun `state changes when button is pressed`() {
        var pressedState by mutableStateOf(false)

        composeTestRule.setContent {
            Box {
                AppButton(
                    text = "Test",
                    onClick = { pressedState = !pressedState }
                )
            }
        }

        val buttonNode = composeTestRule.onNodeWithText("Test")
        buttonNode.assertIsDisplayed()

        // Initial state
        assert(!pressedState)

        // Click toggles state
        buttonNode.performClick()
        assert(pressedState)
    }
}