package com.example.studygroup


import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import components.DropDown
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith


/**
 * Instrumented tests for DropDown
 *
 * These are generated by ChatGPT
 */
@RunWith(AndroidJUnit4::class)
class DropDownInstrumentedTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<TestActivity>()

    @Test
    fun `see if options can be clicked`() {
        // Mock options
        val options = listOf(
            mapOf("subjectCode" to "PROG2007", "subjectName" to "Mobile"),
            mapOf("subjectCode" to "IDATG2102", "subjectName" to "Algmet")
        )

        var selectedItem: Map<String, Any>? = null
        var dismissed = false

        composeTestRule.setContent {
            DropDown(
                text = "Add subject",
                options = options,
                onSelect = { selectedItem = it },
                onDismiss = { dismissed = true }
            )
        }

        // Assert that all options are displayed
        composeTestRule.onNodeWithText("PROG2007 - Mobile").assertIsDisplayed()
        composeTestRule.onNodeWithText("IDATG2102 - Algmet").assertIsDisplayed()
        composeTestRule.onNodeWithText("Add subject").assertIsDisplayed()

        // Click first option
        composeTestRule.onNodeWithText("PROG2007 - Mobile").performClick()
        assert(selectedItem?.get("subjectCode") == "PROG2007")

        // Click dismiss button
        composeTestRule.onNodeWithText("Add subject").performClick()
        assert(dismissed)
    }
}